---
author: "Wei Hern Lim"
title: "DS 202 Homework 2"
date: "2/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Creating table
```{r}
teammates <- matrix(c("Michael Mila", "https://github.com/mmila38/ds202-hw2",  "Wei Hern Lim", "https://github.com/noahwhlim/ds202-hw2"),ncol=2,byrow=TRUE)
colnames(teammates) <- c("Name","Github")
rownames(teammates) <- c("1", "2")
teammates <- as.table(teammates)
teammates
                 
```

## 3 Tips to Make Working With Github Easier  
1. Make sure to leave helpful commit messages whenever commiting  
2. Create branches and tickets when working on something  
3. Keep files organised in the appropriate folders  


## Read csv
```{r}
life5060 <- read.csv("https://raw.githubusercontent.com/ds202-at-isu/materials/master/01_collaborative-environment/data/gapminder-5060.csv")
head(life5060)

```


## Print data for Canada
```{r}
canada <- life5060 %>% filter(country == "Canada")
head(canada)
dim(canada)
```

## Fix data
```{r}
canada_fixed1 = canada
canada_fixed1$lifeExp[canada_fixed1$year==1957] = 69.96
canada_fixed1

canada_fixed <- canada %>% mutate(
  lifeExp = replace(lifeExp, year==1957, 69.96)  
)

canada_fixed %>% ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_line()
```



